In [58]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split as tts
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [59]:
df = pd.read_csv('weight-height.csv')
df1 = pd.read_csv('weight-height.csv')
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

# Encoding

In [60]:
encoder = LabelEncoder()

In [61]:
df.Gender = encoder.fit_transform(df.Gender)

In [62]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [79]:
x = df[['Height','Weight']]
y = df['Gender']
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [80]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Gender, dtype: int32

# data split

In [81]:
xtrain, xtest, ytrain, ytest = tts(x,y ,train_size = 0.70, random_state = 1)

# KNeighborsRegressor

In [82]:
knn = KNeighborsRegressor(n_neighbors = 200)

In [83]:
knn.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=200)

In [84]:
predict_knn_value = knn.predict(xtest)

In [85]:
predict_knn_value

array([0.6  , 0.945, 0.98 , ..., 0.21 , 0.825, 0.99 ])

In [86]:
mse = mean_squared_error(ytest, predict_knn_value)

In [87]:
mse

0.060056320607713286

In [88]:
mae = mean_absolute_error(ytest, predict_knn_value)

In [89]:
mae

0.12346123880015585

In [90]:
knn.score(xtest,ytest)

0.7519117430069711

# LinearRegression

In [91]:
lr = LinearRegression()

In [92]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [93]:
predict_lr_value = lr.predict(xtest)

In [94]:
predict_lr_value

array([0.57393956, 0.73951033, 0.8207258 , ..., 0.34009443, 0.57491606,
       0.8940418 ])

In [95]:
mse = mean_squared_error(ytest, predict_lr_value)
mse

0.08405293100951133

In [96]:
mae = mean_absolute_error(ytest, predict_lr_value)
mae

0.23503850687795877

In [97]:
lr.score(xtest,ytest)

0.6527835049117745

# KNN classification

In [98]:
a = df[['Height','Weight']]
b = df['Gender']
a.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [104]:
atrain, atest, btrain, btest = tts(a,b, train_size = 0.70, random_state = 42)

In [105]:
knn_clf = KNeighborsClassifier()

In [106]:
knn_clf.fit(atrain, btrain)

KNeighborsClassifier()

In [107]:
ypred_clf =knn_clf.predict(atest)
ypred_clf

array([0, 1, 1, ..., 0, 1, 0])

In [108]:
knn_clf.score(atest,btest)

0.9131281651733542